FROM node:20-slim
WORKDIR /app

RUN npm install -g pnpm@9

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --ignore-scripts

COPY tsconfig.json ./
COPY src/ ./src/

RUN pnpm exec tsc

EXPOSE 9002
CMD ["node", "dist/axl-broker/server.js"]
